# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72719e2110ebc2c7fcc593762b8b85c762215da99d62349ecfbe2e7c7a533f30ea93e940993e12a3a13aca5c6f6298a6cc2b47d1661ab579a52ee79fa7d7a90a

test:
  secret_key_base: 380453d92311a556134e3d371c6ff1aba95401249ec8bc4e9119c3ef6dbf95f73d53355844d47a53ec4aae1b29e2ed55a559da36f56464398dc91094b18d90de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
